import { StyleSheet } from 'react-native';
import { ColorsType } from '../../../../constants/Ui/colors/colors.types';

export const useStyles = (colors: ColorsType) =>
    StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: colors.background_primary,
        },
        header: {
            flexDirection: 'row',
            alignItems: 'center',
            paddingHorizontal: 24,
            paddingVertical: 16,
        },
        redIndicator: {
            width: 4,
            height: 48,
            backgroundColor: '#E2231A',
            borderRadius: 2,
        },
        logoContainer: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 12,
            marginLeft: 16,
        },
        logo: {
            width: 40,
            height: 40,
            resizeMode: 'contain',
        },
        titleWrapper: {
            justifyContent: 'center',
        },
        logoTitle: {
            fontSize: 22,
            lineHeight: 24,
            color: '#707A3E',
            fontWeight: 'bold',
            letterSpacing: 1.5,
        },
        logoSubtitle: {
            fontSize: 10,
            lineHeight: 12,
            color: '#B5BA95',
            fontWeight: '500',
        },
        mapContainer: {
            flex: 1,
            marginHorizontal: 24,
            marginVertical: 16,
            borderRadius: 24,
            overflow: 'hidden',
            backgroundColor: '#F5F5F5',
            position: 'relative',
        },
        mapImage: {
            width: '100%',
            height: '100%',
            resizeMode: 'cover',
        },
        coordinateInspector: {
            position: 'absolute',
            top: 16,
            left: 16,
            right: 16,
            paddingHorizontal: 14,
            paddingVertical: 10,
            borderRadius: 10,
            backgroundColor: 'rgba(0, 38, 102, 0.88)',
        },
        coordinateInspectorTitle: {
            color: '#A9D1FF',
            fontSize: 12,
            fontWeight: '700',
        },
        coordinateInspectorValue: {
            color: '#FFFFFF',
            fontSize: 14,
            fontWeight: '700',
            marginTop: 2,
        },
        coordinateInspectorHint: {
            color: '#D8E9FF',
            fontSize: 11,
            marginTop: 3,
        },
        routeOverlay: {
            ...StyleSheet.absoluteFillObject,
        },
        targetCircle: {
            position: 'absolute',
            width: 32,
            height: 32,
            borderRadius: 16,
            borderWidth: 4,
            borderColor: '#D4FF00',
            backgroundColor: 'rgba(212, 255, 0, 0.25)',
            justifyContent: 'center',
            alignItems: 'center',
        },
        targetDot: {
            width: 10,
            height: 10,
            borderRadius: 5,
            backgroundColor: '#D4FF00',
        },
        arrowHead: {
            position: 'absolute',
            width: 0,
            height: 0,
            backgroundColor: 'transparent',
            borderStyle: 'solid',
            borderLeftWidth: 10,
            borderRightWidth: 10,
            borderBottomWidth: 18,
            borderLeftColor: 'transparent',
            borderRightColor: 'transparent',
            borderBottomColor: '#00A3FF',
        },
        floorSelectorContainer: {
            position: 'absolute',
            right: 16,
            bottom: 24,
            gap: 8,
        },
        floorButton: {
            width: 48,
            height: 48,
            borderRadius: 12,
            backgroundColor: 'rgba(255, 255, 255, 0.9)',
            justifyContent: 'center',
            alignItems: 'center',
            elevation: 3,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.15,
            shadowRadius: 3,
        },
        floorButtonActive: {
            backgroundColor: '#E2231A',
        },
        floorText: {
            fontSize: 15,
            fontWeight: 'bold',
            color: '#333333',
        },
        floorTextActive: {
            color: '#FFFFFF',
        },
        zoomHUD: {
            position: 'absolute',
            left: 16,
            bottom: 24,
            gap: 8,
        },
        zoomButton: {
            width: 48,
            height: 48,
            borderRadius: 12,
            backgroundColor: 'rgba(255, 255, 255, 0.9)',
            justifyContent: 'center',
            alignItems: 'center',
            elevation: 3,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.15,
            shadowRadius: 3,
        },
        zoomText: {
            fontSize: 24,
            fontWeight: 'bold',
            color: '#333333',
        },
        footer: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            paddingHorizontal: 24,
            paddingVertical: 20,
            borderTopWidth: 1,
            borderTopColor: '#EEEEEE',
            backgroundColor: '#FFFFFF',
        },
        btnBack: {
            flex: 1,
            height: 56,
            borderRadius: 28,
            borderWidth: 1,
            borderColor: '#EEEEEE',
            justifyContent: 'center',
            alignItems: 'center',
            marginRight: 16,
        },
        btnBackText: {
            color: '#333333',
            fontSize: 16,
            fontWeight: 'bold',
        },
        btnAction: {
            flex: 1.2,
            height: 56,
            borderRadius: 28,
            backgroundColor: '#E2231A',
            justifyContent: 'center',
            alignItems: 'center',
        },
        btnActionText: {
            color: '#FFFFFF',
            fontSize: 16,
            fontWeight: 'bold',
        },
    });
